version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_task_manager
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # Root password
      MYSQL_DATABASE: task_db     # Database to create
      MYSQL_USER: taskuser                # Non-root user to create
      MYSQL_PASSWORD: taskpassword        # Password for the user
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./logs:/logs

  adminer:
    image: adminer
    container_name: adminer_task_dashboard
    restart: always
    ports:
      - "8088:8080"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Expose Redis on default port
    #command: [ "redis-server", "--requirepass", "your_redis_password" ]  # Optional: Secure Redis with a password
    volumes:
      - redis-data:/data

volumes:
    redis-data:  # Define the volume for Redis

