version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_task_manager
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # Root password
      MYSQL_DATABASE: task_db     # Database to create
      MYSQL_USER: taskuser                # Non-root user to create
      MYSQL_PASSWORD: taskpassword        # Password for the user
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_task_dashboard
    restart: always
    ports:
      - "8088:8080"
